export { default as AboutView } from './About'
export { default as ArticleView } from './Article'
export { default as BlogView } from './Blog'
export { default as CategoryView } from './Category'
export { default as ContactView } from './Contact'
export { default as HomeView } from './Home'
export { default as ProjectDetailView } from './ProjectDetail'
export { default as ProjectsView } from './Projects'
